module LazyNcaa
  TEAMS = [
    'Kansas',
    'Villanova',
    'Miami (FL)',
    'California',
    'Maryland',
    'Arizona',
    'Iowa',
    'Colorado',
    'UConn',
    'Temple',
    'Van/Wich',
    'South Dak St',
    'Hawaii',
    'Buffalo',
    'UNC Asheville',
    'Austin Peay',

    'Oregon',
    'Oklahoma',
    'Texas A&M',
    'Duke',
    'Baylor',
    'Texas',
    'Oregon St',
    'St Joes',
    'Cincinnati',
    'VCU',
    'N Iowa',
    'Yale',
    'UNCW',
    'UW Green Bay',
    'CSU Bakersfield',
    'HC/South',

    'North Carolina',
    'Xavier',
    'West Virginia',
    'Kentucky',
    'Indiana',
    'Notre Dame',
    'Wisconsin',
    'USC',
    'Providence',
    'Pittsburgh',
    'MICH/TULSA',
    'Chattanooga',
    'Stony Brook',
    'SF Austin',
    'Weber St',
    'FGCU/FDU',

    'Virginia',
    'Michigan St',
    'Utah',
    'Iowa St',
    'Purdue',
    'Seton Hall',
    'Dayton',
    'Texas Tech',
    'Butler',
    'Syracuse',
    'Gonzaga',
    'Ark Little Rock',
    'Iona',
    'Fresno St',
    'Mid Tennessee',
    'Hampton'
  ]
end
