module LazyNcaa
  TEAMS = [
    'Kentucky',
    'Kansas',
    'Notre Dame',
    'Maryland',
    'West Virginia',
    'Butler',
    'Wichita St',
    'Cincinnati',
    'Purdue',
    'Indiana',
    'Texas',
    'Buffalo',
    'Valparaiso',
    'Northeastern',
    'New Mexico St',
    'Manhattan/Hampton',

    'Wisconsin',
    'Arizona',
    'Baylor',
    'North Carolina',
    'Arkansas',
    'Xavier',
    'VCU',
    'Oregon',
    'OK State',
    'Ohio St',
    'BYU/Ole Miss',
    'Wofford',
    'Harvard',
    'Georgia St',
    'Texas SO',
    'Coastal Carolina',

    'Villanova',
    'Virginia',
    'Oklahoma',
    'Louisville',
    'Northern Iowa',
    'Providence',
    'Michigan St',
    'NC State',
    'LSU',
    'Georgia',
    'Boise St/Dayton',
    'Wyoming',
    'UC Irvine',
    'Albany',
    'Belmont',
    'Lafayette',

    'Duke',
    'Gonzaga',
    'Iowa St',
    'Georgetown',
    'Utah',
    'SMU',
    'Iowa',
    'San Diego St',
    'St Johns',
    'Davidson',
    'UCLA',
    'SF Austin',
    'Eastern Wash',
    'UAB',
    'N Dakota St',
    'N Fla/Rob Morris'
  ]
end
