module LazyNcaa
  TEAMS = [
    'Florida',
    'Kansas',
    'Syracuse',
    'UCLA',
    'VCU',
    'Ohio St',
    'New Mexico',
    'Colorado',
    'Pittsburgh',
    'Stanford',
    'Dayton',
    'S.F. Austin',
    'Tulsa',
    'W Michigan',
    'E Kentucky',
    'Alb/M St Mary',

    'Virginia',
    'Villanova',
    'Iowa St',
    'Michigan St',
    'Cincinnati',
    'N Carolina',
    'Connecticut',
    'Memphis',
    'G Washington',
    'St Joseph',
    'Providence',
    'Harvard',
    'Delaware',
    'NC Central',
    'UW-Milwaukee',
    'Coastal Car.',

    'Arizona',
    'Wisconsin',
    'Creighton',
    'San Diego St',
    'Oklahoma',
    'Baylor',
    'Oregon',
    'Gonzaga',
    'OK State',
    'BYU',
    'Nebraska',
    'N Dakota St',
    'N Mexico St',
    'Lou. Lafayette',
    'American U',
    'Weber St',

    'Witchita St',
    'Michigan',
    'Duke',
    'Louisville',
    'St Louis',
    'Massachusetts',
    'Texas',
    'Kentucky',
    'Kansas St',
    'Arizona St',
    'Iowa/Tenn',
    'NC St/Xavier',
    'Manhattan',
    'Mercer',
    'Wofford',
    'CalPoly/TX So.'
  ]
end
